name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Parse Azure credentials
      id: parse_creds
      run: |
        echo '${{ secrets.AZURE_CREDENTIALS }}' > creds.json
        echo "ARM_CLIENT_ID=$(jq -r .clientId creds.json)" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret creds.json)" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=$(jq -r .tenantId creds.json)" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Show Public IP
      run: terraform output public_ip
      
    - name: Install jq
      run: sudo apt-get install -y jq
